---
application:
  root: C:/
environment: {}
#messaging:
 #/queues/test_queue:  TestConsumer
stomp:
  host: 192.168.2.130
  stomplets:
    simple:
      class: Simple
      route: '/stomplet/simple'
      config:
        destination: /queues/test_queue
        type: queue
