---
application:
  root: C:/
environment: {}
queues:
  /queues/test_queue:
messaging:
 /queues/test_queue:  TestConsumer
stomp:
  host: 192.168.2.130
  stomplets:
    stomplet.one:
      class: Simple
      route: '/stomplets/simple'
      config:
        destination: /queues/test_queue
        type: queue
