---
application:
  root: C:/
environment: {}
queues:
  /queues/test_queue:
messaging:
 /queues/test_queue:  TestConsumer
stomp:
  host: localhost
  stomplets:
    stomplet.one:
      class: TestStompletController
      route: '/controllers/test_stomplet_controller'
      config:
        destination: /queues/test_queue
        type: queue
